---

- name : "Instalacja podstawowych narzedzi"
  hosts: "{{ var_host }}"
  tasks:
    - name: Narzedzia podstawowe
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - sysstat
        - htop
        - glances
        - dnsutils
        - tcpdump
        - net-tools
        - htop
        - whois
        - iperf
        - dstat
        - tshark
        - bonnie++
        - telnet
        - traceroute
        - nmap
        - iotop
        - dstat
        - mtr
        - bwm-ng
        - strace
        - mc
        - net-tools
        - git-core
        - mailutils
        - fish
