---

- name : "Instalacja klienta MFS"
  hosts: "{{ var_host }}"
  tasks:
    - name: Add MFS official GPG key
      apt_key:
        url: http://ppa.moosefs.com/moosefs.key
        state: present
    - name: Add MFS repository
      apt_repository:
         repo: 'deb http://ppa.moosefs.com/3.0.112/apt/ubuntu/bionic bionic main'
         state: present
         filename: mfc_client
         update_cache: yes
    - name: moosefs binaries
      apt:
        name: moosefs-pro-client
        state: present
