---

- name : "Instalacja podstawowego monitoringu. Zabbix i monit"
  hosts: "{{ var_host }}"
  tasks:
    - name: Monitoring
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - zabbix-agent
        - monit
        - ssmtp
        - mailutils
